### ISSUE TITLE
Meta: Improve the app's design

### ISSUE THREAD

**Issue by YaronMiro** [shoov/shoov#238]
**Improve the app design:**
This is a meta issue, smaller issues were opened for each task
- [x]  Discovery - responsive framework with support for 2 major breakpoints. #239
- [x] Adapt responsive framework (support for 2 major breakpoints). #240
- [x] Header & Breadcrumbs design. #241
- [x] Footer design. #242
- [x] Login page design. #243
- [x] Account page design. #244
- [x] Live Monitor page design (repos). #245
- [x] Visual Regression page design (builds). #246
- [x] Dashboard page design. #256 
- [x] Encrypt  page design. #274 
- [ ] Screenshot  page design. #275 
- [x] Repo page design. #276
- [x] ci-incidents page design #279
- [x] ci-build-items page design #280

**Comment by YaronMiro** [comment]
@amitaibu 
Please extend my permission on this repository. Current status is that I cannot create a label or assignee to issues.
Thanks

**Comment by amitaibu** [comment]
> Please extend my permission on this repository

Done.

**Comment by amitaibu** [comment]
Deployed, and looks so much better. Kudos!
